### PR TITLE
Added fixes for backlight toggle, cursor moving, and newline characters within "lcd.message()"

### PR DESCRIPTION
**Pull request by dmanla**
I have been using a PCF8574 based LCD Module. It is a very standard unit.  It is linked below:
https://www.amazon.com/JANSANE-Arduino-Display-Interface-Raspberry/dp/B07D7ZQVDR/

The following fixes have been implemented:

When toggling the backlight it would immediately turn back off. I do not know if this is specific to my LCD Module or not. It has been remedied by modifying all backlight code to mimic the most up to date Adafruit_CircuitPython_CharLCD python module. None of the modifications should negatively affect other LCD Modules.

When changing the cursor position the cursor would move to that position successfully.  When writing a message to the display after moving the cursor the cursor would first move home and then write the message. It is supposed to write the message at the cursor position and then move home. It is functioning properly in my new version of character_lcd.

The newest version of Adafruit_CircuitPython_CharLCD allows the use of newline characters within the lcd.message() function. I have added this functionality.

### CODE REVIEW

**Comment by Tim-Jackins** [comment]
This looks good but I want to find my PCF8574 and test it before merging

**Review by olixr — COMMENTED** [review]
I am looking to test this. I have several PCF modules here I want to use. I was disappointing to find this was not merged into the master repo yet. I'll test this commit and then maybe @Tim-Jackins we can discuss how to get this active and merged into the main repo?

**Comment by Tim-Jackins** [comment]
@olixr That sounds like an excellent idea

**Comment by olixr** [comment]
I have tested the changes with my 1602 LCD module that has an I2C backpack (PCF chip). The code with changes is working well. I had some issues trying to get your PCF driver (https://github.com/Tim-Jackins/pcf8574/blob/master/pcf8574.py). What is the easiest way to do that? I ended up copying it and doing a local reference for testing.

I also posted on the main adafruit thread here https://github.com/adafruit/Adafruit_CircuitPython_CharLCD/issues/29

They mentioned some ways to check out updates. I am more of a web technologies specialist but am working on a garden project called MudPi that is making use of this library. I have been cobbling together fixes I can to try and get support for multiple LCD displays like the old libraries they archived.

**Review by olixr — APPROVED** [review]
Tested on 1602 i2c backpack using PCF chip. Working.

**Comment by Tim-Jackins** [comment]
@olixr I would just copy it onto your circuitpython device. Is the a handy way to do package management for circuitpython? Also, MudPi looks super cool!

**Comment by olixr** [comment]
I am not using a circuitpython device persay. I am installing packages via `pip` to my Raspberry Pi. More specifically I was using this library for the Pi to drive the LCD displays on my main units. I wrote things to run in python 3 on the Pi. 

In the meantime I will be working on getting these changes merged to the main repo with you. I am still trying to figure out if they are wanting to add support into the `Adafruit_CircuitPython_CharLCD` library or keep support separated out into `dhalbert/CircuitPython_LCD`. It would be nice if they keep the same syntax for both packages.

**Pull request merged**
